### PR TITLE
Move non ui npm module to mono repo

### PR DESCRIPTION
**Pull request by OR13**
Moving the non ui wallet related code out of this repo.

Hoping to add more examples, using aries framework go, and other wallet libs and keep this repo focused on spec and ui and not wallet implementation details.

### CODE REVIEW

**Review by kimdhamilton — CHANGES_REQUESTED** [review]
I need some more context. Where is the code going? (i.e. which mono repo is it going to?)

It's hard to get a sense of the direction from the PR.

**Comment by OR13** [comment]
@kimdhamilton all the npm modules in the repo are currently under `@transmute`, and the latest versions of them are now hosted here: https://github.com/transmute-industries/linked-data/tree/main/packages/universal-wallet

Its difficult to manage our wallet implementation `@transmute/universal-wallet` in the ccg, and we also don't want to diminish the work @sudeshrshetty and others are doing on implementing the spec and its interfaces.

This PR just moves npm package code under our github organization (we already controlled the packages before).

This module: https://github.com/w3c-ccg/universal-wallet-interop-spec/tree/master/packages/universal-wallet-react

hosts the react and material ui components associated with the spec.

technically its also name-spaced under transmute: https://github.com/w3c-ccg/universal-wallet-interop-spec/blob/master/packages/universal-wallet-react/package.json#L2 

I'm not opposed to ccg maintainers forking any of this work or continuing to maintain forks and npm modules in the ccg, but things like CI/CD deployment and integrations with our other software are harder for us for packages under `@transmute` namespace when hosted in the ccg.

End of the day, as a small company we want to be able to move a little faster, and align out wallet implementation of the ccg spec with our other software tooling, etc.

**Comment by kimdhamilton** [comment]
Don't get me wrong, this codebase needs to be refactored (perhaps split into 2 CCG repos), but this changes the scope of this work item.

As a code owner I reject this change.

**Comment by OR13** [comment]
I'm gonna close this and we will open another pr that fixes the npm publishing issue and removes the `@transmute` namespace

**Pull request closed without merging**
